### ISSUE TITLE
Diasporafoundation.org internal server error

### ISSUE THREAD

**Issue by anuyts** [diaspora/diaspora-project-site#98] opened 2017-02-05 06:50 UTC
The website diasporafoundation.org has a language menu. When I pick "Nederlands", I get an internal server error (500). Because the language setting is not stored in the URL, going back without language menu seems impossible, and the menu is gone.
To be clear: the primary problem is not that the translation is missing, but that you cannot go back.
First filed [here](https://github.com/diaspora/diaspora/issues/7308).

**Comment by goobertron** [comment] 2017-02-05 13:06
Related to #97. This should have been fixed by  fa7ef2e and fdd29e2. @denschub, looks like there's a but more fixing needed, I'm afraid.

**Comment by denschub** [comment] 2017-02-06 10:40
> looks like there's a but more fixing needed, I'm afraid.

Well, that's the fun of replacing placeholders inside translations. There is nothing I can do, this has to be fixed on WTI for all locales.

**Comment by goobertron** [comment] 2017-02-06 12:19
I thought locales were supposed to fall back to another language (ultimately to English) if there was not a translation for a particular string. It's not good if a missing translation breaks the entire site. Is there no way around that?

As a last resort, and if there's not a better means of coping with missing strings, how about adding empty strings (`""`) to the locale files where there is not (yet) a translation?

**Comment by denschub** [comment] 2017-02-06 14:05
> It's not good if a missing translation breaks the entire site. Is there no way around that?

It's not a missing translation, it's the mere fact the placeholder `poduptime` doesn't exist anymore since it was removed.

**Closed** 2017-02-06 14:13 UTC

**Comment by denschub** [comment] 2017-02-06 14:15
Deployed [a ghetto hack](https://github.com/diaspora/diaspora-project-site/commit/ec81dfdbd6646c5da86a0cd88f9edb3c4e62b610) since it's breaking the index page and I don't have the time to go through all translations.

**Comment by Flaburgan** [comment] 2017-02-06 14:56
I think @cmrd-senya checked all the index page on saturday evening and only Nertherland was broken (can you confirm senya?)

**Comment by denschub** [comment] 2017-02-06 14:59
I can confirm that, since I just used some grep and sed magic. That's why I already removed the ghetto hack and purged the Dutch translation of that key. ;)

**Comment by goobertron** [comment] 2017-02-06 21:18
Thanks very much indeed, @denschub, for your work on this!
